### ISSUE TITLE
Error: Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by UtkarshMishr** [RallyTools/rally-node#35]
Getting below error

{ Error: Error: unable to get local issuer certificate
    at generateError (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\rally\dist\request.js:38:11)
    at Request._callback (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\rally\dist\request.js:110:20)
    at self.callback (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\request\request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\request\request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
  errors:
   [ { Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } ] }
(node:9540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: unable to get local issuer cert
(node:9540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not hand
minate the Node.js process with a non-zero exit code.
{ Error: Error: unable to get local issuer certificate
    at generateError (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\rally\dist\request.js:38:11)
    at Request._callback (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\rally\dist\request.js:110:20)
    at self.callback (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\request\request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\mishrut\full_stack\gitlab_rally_alm\node_modules\request\request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
  errors:
   [ { Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' } ] }
(node:9540) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Error: unable to get local issuer cert

**Comment by krmorse** [comment]
Sounds like your company network is using a cert in its proxy that your code doesn't trust: https://github.com/nodejs/node/issues/3742

**Comment by nsdeo12** [comment]
possible solution :https://stackoverflow.com/questions/46968937/nodejs-request-post-not-working-for-https-website/46968984#46968984
